#!/usr/bin/env python3
"""
add_article.py — Convert a .docx file to a native article on the portfolio site.

Usage:
    python add_article.py path/to/article.docx

Requirements:
    pip install -r requirements.txt
"""

import sys
import os
import re
import mammoth
from datetime import date


def slugify(title):
    """Convert a title to a URL-friendly slug."""
    slug = title.lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    slug = re.sub(r"[\s_]+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    return slug.strip("-")


def camel_case(slug):
    """Convert a slug to camelCase for JS variable names."""
    parts = slug.split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def escape_template_literal(text):
    """Escape characters that would break a JS template literal."""
    text = text.replace("\\", "\\\\")
    text = text.replace("`", "\\`")
    text = text.replace("${", "\\${")
    return text


def docx_to_markdown(docx_path):
    """Convert a .docx file to Markdown using mammoth."""
    with open(docx_path, "rb") as f:
        result = mammoth.convert_to_markdown(f)
    if result.messages:
        print("  Conversion warnings:")
        for msg in result.messages:
            print(f"    - {msg}")
    return result.value


def generate_article_js(slug, var_name, title, description, article_date, tags, featured, content):
    """Generate the JS module for src/articles/{slug}.js."""
    default_image = "  image: require('../assets/articles/default.png'), // TODO: update filename"
    return generate_article_js_with_image(
        slug, var_name, title, description, article_date, tags, featured, content, default_image
    )


def parse_existing_article(article_path):
    """Extract metadata from an already-generated article JS file."""
    with open(article_path, "r", encoding="utf-8") as f:
        text = f.read()

    def get_single_quoted(field):
        m = re.search(rf"{field}:\s*'((?:[^'\\]|\\.)*)'", text)
        return m.group(1).replace("\\'", "'") if m else ""

    title = get_single_quoted("title")
    description = get_single_quoted("description")
    article_date = get_single_quoted("date")

    tags = []
    m = re.search(r"tags:\s*\[(.*?)\]", text)
    if m and m.group(1).strip():
        tags = [t.strip().strip("'\"") for t in m.group(1).split(",") if t.strip()]

    featured = True
    m = re.search(r"featured:\s*(true|false)", text)
    if m:
        featured = m.group(1) == "true"

    # Preserve the existing image require() line so we don't clobber a custom image
    image_line = "  image: require('../assets/articles/default.png'), // TODO: update filename"
    m = re.search(r"  image:.*", text)
    if m:
        image_line = m.group(0)

    return title, description, article_date, tags, featured, image_line


def generate_article_js_with_image(slug, var_name, title, description, article_date, tags, featured, content, image_line):
    """Like generate_article_js but uses a caller-supplied image line."""
    today = date.today().isoformat()
    tags_js = ", ".join(f"'{tag}'" for tag in tags)
    featured_js = "true" if featured else "false"
    safe_title = title.replace("'", "\\'")
    safe_description = description.replace("'", "\\'")

    return (
        f"// Generated by add_article.py on {today}\n"
        f"// To add a cover image:\n"
        f"//   1. Copy your image to src/assets/articles/\n"
        f"//   2. Change the require() path below to your image filename\n"
        f"\n"
        f"const {var_name} = {{\n"
        f"  id: '{slug}',\n"
        f"  title: '{safe_title}',\n"
        f"  description: '{safe_description}',\n"
        f"  date: '{article_date}',\n"
        f"  type: 'internal',\n"
        f"{image_line}\n"
        f"  tags: [{tags_js}],\n"
        f"  featured: {featured_js},\n"
        f"  content: `{content}`\n"
        f"}};\n"
        f"\n"
        f"export default {var_name};\n"
    )


def update_articles_data(slug, var_name):
    """
    Inject an import and a reference into src/components/articlesData.js.

    - Import is inserted just before 'export const articles = ['
    - Article reference is inserted as the first entry in the array
    """
    script_dir = os.path.dirname(os.path.abspath(__file__))
    articles_data_path = os.path.join(script_dir, "src", "components", "articlesData.js")

    with open(articles_data_path, "r", encoding="utf-8") as f:
        content = f.read()

    import_line = f"import {var_name} from '../articles/{slug}';"

    # --- Inject import ---
    if import_line in content:
        print(f"  (import for {var_name} already present, skipping)")
    else:
        # Insert the import line directly before 'export const articles'
        content = re.sub(
            r"(export const articles = \[)",
            f"{import_line}\n\n\\1",
            content,
        )

    # --- Inject article reference as first array entry ---
    article_ref = f"  {var_name},"
    if article_ref in content:
        print(f"  ({var_name} already in articles array, skipping)")
    else:
        # Insert after the opening bracket of the articles array
        content = re.sub(
            r"(export const articles = \[)\n",
            f"\\1\n{article_ref}\n",
            content,
        )

    with open(articles_data_path, "w", encoding="utf-8") as f:
        f.write(content)


def main():
    if len(sys.argv) != 2:
        print("Usage: python add_article.py path/to/article.docx")
        sys.exit(1)

    docx_path = sys.argv[1]
    if not os.path.isfile(docx_path):
        print(f"Error: file not found: {docx_path}")
        sys.exit(1)

    print(f"\nConverting '{docx_path}' to Markdown...")
    markdown_raw = docx_to_markdown(docx_path)
    content = escape_template_literal(markdown_raw)
    print("Conversion complete.\n")

    # --- Interactive prompts ---
    title = input("Article title: ").strip()
    if not title:
        print("Error: title cannot be empty.")
        sys.exit(1)

    slug = slugify(title)
    var_name = camel_case(slug) + "Article"
    print(f"  → Slug: {slug}")

    script_dir = os.path.dirname(os.path.abspath(__file__))
    articles_dir = os.path.join(script_dir, "src", "articles")
    os.makedirs(articles_dir, exist_ok=True)
    article_path = os.path.join(articles_dir, f"{slug}.js")

    # --- Update mode: article already exists ---
    if os.path.isfile(article_path):
        print(f"\n  Article already exists — updating content only.")
        ex_title, ex_description, ex_date, ex_tags, ex_featured, ex_image = parse_existing_article(article_path)
        print(f"  Preserving:")
        print(f"    title:       {ex_title}")
        print(f"    date:        {ex_date}")
        print(f"    description: {ex_description}")
        print(f"    tags:        {', '.join(ex_tags)}")
        print(f"    featured:    {ex_featured}")

        article_js = generate_article_js_with_image(
            slug, var_name, ex_title, ex_description, ex_date, ex_tags, ex_featured, content, ex_image
        )
        with open(article_path, "w", encoding="utf-8") as f:
            f.write(article_js)
        print(f"\nUpdated:  {article_path}")
        update_articles_data(slug, var_name)
        print(f"Checked:  src/components/articlesData.js (no changes needed)")
        print(
            f"\nDone! Content refreshed.\n"
            f"  npm start   → preview at /#/articles/{slug}\n"
            f"  npm run build && npm run deploy   → publish\n"
        )
        return

    # --- New article mode ---
    today = date.today().isoformat()
    date_input = input(f"Date [{today}]: ").strip()
    article_date = date_input if date_input else today

    description = input("Description (1-2 sentences): ").strip()

    tags_input = input("Tags (comma-separated, e.g. AI, Python, Data): ").strip()
    tags = [t.strip() for t in tags_input.split(",") if t.strip()]

    featured_input = input("Featured? (y/n) [y]: ").strip().lower()
    featured = featured_input != "n"

    article_js = generate_article_js(
        slug, var_name, title, description, article_date, tags, featured, content
    )

    with open(article_path, "w", encoding="utf-8") as f:
        f.write(article_js)
    print(f"\nCreated:  {article_path}")

    # --- Update articlesData.js ---
    update_articles_data(slug, var_name)
    print(f"Updated:  src/components/articlesData.js")

    print(
        f"\nDone! Next steps:\n"
        f"  1. Add a cover image to src/assets/articles/\n"
        f"  2. Update the require() path in {article_path}\n"
        f"  3. npm start   → preview at /#/articles/{slug}\n"
        f"  4. npm run build && npm run deploy   → publish\n"
    )


if __name__ == "__main__":
    main()
