// Book recommendations data with 10-point rating system

export const books = [
  {
    id: 'unfuck-your-brain',
    title: 'Unfuck Your Brain',
    author: 'Dr. Faith Harper',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Psychology', 'Mental Health', 'Self-Help'],
    coverImage: null,
  },
  {
    id: 'little-book-ikigai',
    title: 'Little Book of Ikigai',
    author: 'Ken Mogi',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Philosophy', 'Japanese Culture', 'Purpose'],
    coverImage: null,
  },
  {
    id: 'nagomi',
    title: 'Nagomi',
    author: 'Ken Mogi',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Philosophy', 'Japanese Culture', 'Balance'],
    coverImage: null,
  },
  {
    id: 'tiny-habits',
    title: 'Tiny Habits',
    author: 'B.J. Fogg',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Productivity', 'Habits', 'Behavior Change'],
    coverImage: null,
  },
  {
    id: 'feel-good-productivity',
    title: 'Feel Good Productivity',
    author: 'Ali Abdaal',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Productivity', 'Well-being', 'Self-Help'],
    coverImage: null,
  },
  {
    id: 'thinking-fast-slow',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Psychology', 'Behavioral Economics', 'Decision Making'],
    coverImage: null,
  },
  {
    id: 'hacker-mindset',
    title: 'The Hacker Mindset',
    author: 'Garrett Gee',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Business', 'Entrepreneurship', 'Mindset'],
    coverImage: null,
  },
  {
    id: 'stolen-focus',
    title: 'Stolen Focus',
    author: 'Johann Hari',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Psychology', 'Attention', 'Modern Life'],
    coverImage: null,
  },
  {
    id: 'courage-is-calling',
    title: 'Courage is Calling',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Stoicism', 'Philosophy', 'Courage'],
    coverImage: null,
  },
  {
    id: 'dose-effect',
    title: 'The DOSE Effect',
    author: 'TJ Power',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Neuroscience', 'Well-being', 'Psychology'],
    coverImage: null,
  },
  {
    id: 'discipline-is-destiny',
    title: 'Discipline Is Destiny',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Stoicism', 'Philosophy', 'Self-Discipline'],
    coverImage: null,
  },
  {
    id: 'hooked',
    title: 'Hooked',
    author: 'Nir Eyal',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Product Design', 'Psychology', 'Business'],
    coverImage: null,
  },
  {
    id: 'slow-productivity',
    title: 'Slow Productivity',
    author: 'Cal Newport',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Productivity', 'Work Culture', 'Deep Work'],
    coverImage: null,
  },
  {
    id: 'digital-minimalism',
    title: 'Digital Minimalism',
    author: 'Cal Newport',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Minimalism', 'Technology', 'Well-being'],
    coverImage: null,
  },
  {
    id: 'five-types-wealth',
    title: 'The 5 Types of Wealth',
    author: 'Sahil Bloom',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Personal Finance', 'Well-being', 'Life Philosophy'],
    coverImage: null,
  },
  {
    id: 'right-thing-right-now',
    title: 'Right Thing, Right Now',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Stoicism', 'Philosophy', 'Decision Making'],
    coverImage: null,
  },
  {
    id: 'comfort-crisis',
    title: 'The Comfort Crisis',
    author: 'Michael Easter',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Health', 'Psychology', 'Modern Life'],
    coverImage: null,
  },
  {
    id: 'million-dollar-weekend',
    title: 'Million Dollar Weekend',
    author: 'Noah Kagan',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Entrepreneurship', 'Business', 'Startup'],
    coverImage: null,
  },
  {
    id: 'obstacle-is-way',
    title: 'The Obstacle Is the Way',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Stoicism', 'Philosophy', 'Resilience'],
    coverImage: null,
  },
  {
    id: 'scarcity-brain',
    title: 'Scarcity Brain',
    author: 'Michael Easter',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Psychology', 'Neuroscience', 'Behavior'],
    coverImage: null,
  },
  {
    id: 'stillness-is-key',
    title: 'Stillness Is the Key',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Stoicism', 'Philosophy', 'Mindfulness'],
    coverImage: null,
  },
  {
    id: 'book-of-charlie',
    title: 'The Book of Charlie',
    author: 'David Von Drehle',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Biography', 'Life Lessons', 'Wisdom'],
    coverImage: null,
  },
  {
    id: 'so-good-cant-ignore',
    title: "So Good They Can't Ignore You",
    author: 'Cal Newport',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Career', 'Skills', 'Success'],
    coverImage: null,
  },
  {
    id: 'founder-force-multiplier',
    title: 'The Founder & The Force Multiplier',
    author: 'Adama Hergenrother',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Business', 'Leadership', 'Entrepreneurship'],
    coverImage: null,
  },
  {
    id: 'essentialism',
    title: 'Essentialism',
    author: 'Greg McKeown',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Productivity', 'Minimalism', 'Focus'],
    coverImage: null,
  },
  {
    id: 'twelve-week-year',
    title: 'The 12 Week Year',
    author: 'Brian Moran',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Productivity', 'Goal Setting', 'Time Management'],
    coverImage: null,
  },
  {
    id: 'building-second-brain',
    title: 'Building a Second Brain',
    author: 'Thiago Forte',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Productivity', 'Knowledge Management', 'Organization'],
    coverImage: null,
  },
  {
    id: 'adhd-advantage',
    title: 'Unblocking the ADHD Advantage',
    author: 'Dr. Anders Hansen',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['ADHD', 'Neuroscience', 'Psychology'],
    coverImage: null,
  },
  {
    id: 'think-again',
    title: 'Think Again',
    author: 'Adam Grant',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Psychology', 'Critical Thinking', 'Learning'],
    coverImage: null,
  },
  {
    id: 'becoming-bulletproof',
    title: 'Becoming Bulletproof',
    author: 'Evy Poumpouras',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Mental Toughness', 'Psychology', 'Security'],
    coverImage: null,
  },
  {
    id: 'psychology-of-money',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Personal Finance', 'Psychology', 'Investing'],
    coverImage: null,
  },
  {
    id: 'wisdom-takes-work',
    title: 'Wisdom Takes Work',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    review: 'Add your review here',
    tags: ['Stoicism', 'Philosophy', 'Wisdom'],
    coverImage: null,
  },
];

// Helper function to get books by rating (for filtering)
export const getBooksByRating = (minRating) => {
  return books.filter(book => book.rating >= minRating);
};

// Helper function to get top rated books
export const getTopRatedBooks = (limit = 5) => {
  return books
    .sort((a, b) => b.rating - a.rating)
    .slice(0, limit);
};

// Helper function to get books by tag
export const getBooksByTag = (tag) => {
  return books.filter(book => book.tags.includes(tag));
};
