// Book recommendations data with 10-point rating system

export const books = [
  {
    id: 'unfuck-your-brain',
    title: 'Unfuck Your Brain',
    author: 'Dr. Faith Harper',
    yearRead: 2025,
    rating: 8,
    review: 'A blunt, science-based guide to understanding why your mind reacts so intensely to stress, anxiety, depression, anger, and trauma. Harper explains how the brain\'s threat systems get rewired by traumatic or chronic stress, leading to overreactions and emotional flooding. Using clear, informal language, she walks through how trauma changes brain pathways and how neuroplasticity allows you to retrain those pathways with new habits, coping skills, and supportive relationships. Each chapter pairs simple neuroscience with practical tools: grounding exercises, self-care practices, harm-reduction strategies, and worksheets that help you name feelings, spot triggers, and monitor moods so you can respond more calmly instead of being hijacked by old patterns.',
    tags: ['Psychology', 'Mental Health', 'Self-Help'],
    coverImage: null,
  },
  {
    id: 'little-book-ikigai',
    title: 'Little Book of Ikigai',
    author: 'Ken Mogi',
    yearRead: 2025,
    rating: 9,
    review: 'A concise yet profound exploration of the Japanese concept of ikigai, which roughly translates to "a reason for being." Mogi, a neuroscientist, breaks down this philosophy into five key pillars: starting small, releasing yourself, harmony and sustainability, the joy of little things, and living in the moment. He shows how everyday happiness in Japan often comes not from grand achievements but from deep engagement with small, meaningful acts. The book blends philosophy, psychology, and cultural insight, showing how finding purpose in everyday routines rewires the brain for contentment. Unlike Western self-help models obsessed with productivity or goals, Mogi\'s perspective is gentler—happiness doesn\'t come from fixing yourself or chasing success, but from being fully present in what you already do.',
    tags: ['Philosophy', 'Japanese Culture', 'Purpose'],
    coverImage: null,
  },
  {
    id: 'nagomi',
    title: 'Nagomi',
    author: 'Ken Mogi',
    yearRead: 2025,
    rating: 9,
    review: 'Explores the Japanese philosophy of finding harmony and balance in a chaotic, fast-changing world. Mogi defines nagomi as a state of emotional ease and calm that comes from blending different, sometimes opposing elements of life into a coherent whole rather than trying to eliminate problems or chase a perfect state. The book is organized around core pillars: maintaining happy relationships even when you disagree, committing to lifelong learning while staying true to yourself, finding peace in whatever you\'re doing, and mixing unlikely components to reach a more stable, resilient balance. Instead of promising a five-step fix, Mogi emphasizes that life is inherently uncertain and that well-being comes from accepting this reality and cultivating harmony with it, not fighting it.',
    tags: ['Philosophy', 'Japanese Culture', 'Balance'],
    coverImage: null,
  },
  {
    id: 'tiny-habits',
    title: 'Tiny Habits',
    author: 'B.J. Fogg',
    yearRead: 2025,
    rating: 10,
    review: 'Presents a science-backed, optimistic approach to lasting behavior change by focusing on making new habits so small and easy that they require almost no motivation to begin. Fogg\'s formula—Behavior = Motivation × Ability × Prompt—shows that success depends less on motivation and more on reducing friction and designing the right trigger. The key is starting with tiny actions (like doing two push-ups after brushing your teeth) and celebrating small victories immediately so your brain associates the behavior with positive emotion. His method blends psychology, habit design, and compassion. Unlike approaches that emphasize discipline or guilt, his focus is on emotion as the true driver of habit formation—feeling good about success is what locks it in. Real change isn\'t about forcing yourself to be different overnight but about designing gentle systems that make good behaviors inevitable and effortless.',
    tags: ['Productivity', 'Habits', 'Behavior Change'],
    coverImage: null,
  },
  {
    id: 'feel-good-productivity',
    title: 'Feel Good Productivity',
    author: 'Ali Abdaal',
    yearRead: 2025,
    rating: 6,
    review: 'Redefines productivity as a byproduct of well-being rather than pressure, burnout, or discipline. Drawing from positive psychology, neuroscience, and his own experience as a doctor turned entrepreneur and creator, Abdaal argues that people are most productive not when they push harder, but when they feel energized, curious, and joyful about what they\'re doing. He flips the typical productivity narrative: instead of squeezing more output from the same hours, focus on how you feel while working, because happiness fuels performance. Each chapter explores practical ways to generate that "feel-good loop" through play, purpose, and peace. Abdaal blends science with tangible tools like energy audits to identify activities that drain or recharge you, habit-stacking for effortless consistency, and frameworks for designing work that feels intrinsically rewarding.',
    tags: ['Productivity', 'Well-being', 'Self-Help'],
    coverImage: null,
  },
  {
    id: 'thinking-fast-slow',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    yearRead: 2025,
    rating: 8,
    review: 'A groundbreaking exploration of how the human mind operates through two distinct systems of thought. System 1 is fast, intuitive, and emotional—it helps you navigate daily life quickly but often jumps to conclusions. System 2 is slow, deliberate, and analytical—it excels at solving complex problems but requires energy and attention, so the brain tends to avoid using it whenever possible. Kahneman, a Nobel Prize-winning psychologist, explains how these systems interact, often leading to predictable errors in judgment called cognitive biases. Through decades of research, he shows how we frequently rely on mental shortcuts like the availability heuristic, anchoring, and overconfidence, which distort our perception of risk, probability, and value. It\'s a manual for better thinking—one that challenges readers to slow down, question instincts, and recognize when emotions drive reasoning.',
    tags: ['Psychology', 'Behavioral Economics', 'Decision Making'],
    coverImage: null,
  },
  {
    id: 'hacker-mindset',
    title: 'The Hacker Mindset',
    author: 'Garrett Gee',
    yearRead: 2025,
    rating: 4,
    review: 'Uses the metaphor of ethical hacking to teach a systematic way to "crack" life\'s systems and achieve freedom on your own terms. Gee argues that most people are unconsciously trained to be "slackers" in life—accepting default paths, corporate structures, and invisible rules—while hackers study systems, find leverage points, and intentionally exploit them to create better outcomes. Drawing on his decades in cybersecurity, he shows that the same skills hackers use on code—curiosity, reverse engineering, probing for weaknesses, and exploiting vulnerabilities—can be used on career paths, financial systems, and personal habits to escape stagnation and design a more autonomous life. The book is organized around a practical 5-step "Hacker Helix" methodology and six guiding principles of the hacker mindset.',
    tags: ['Business', 'Entrepreneurship', 'Mindset'],
    coverImage: null,
  },
  {
    id: 'stolen-focus',
    title: 'Stolen Focus',
    author: 'Johann Hari',
    yearRead: 2025,
    rating: 10,
    review: 'Examines the global attention crisis and argues that our inability to focus is not a personal failure but a systemic problem built into modern life. Drawing from neuroscience, psychology, and extensive interviews with experts, Hari identifies twelve major causes of our collective distraction: from the addictive design of social media and constant notifications to stress, sleep deprivation, pollution, and even declining reading habits. He argues that technology companies and modern work cultures hijack our minds for profit, exploiting our psychological vulnerabilities through algorithms engineered to keep us scrolling, reacting, and consuming information at the expense of depth and creativity. Hari moves beyond critique to offer hope, encouraging readers to reclaim attention both individually and collectively—not just through digital detoxes, but by redesigning the systems around us.',
    tags: ['Psychology', 'Attention', 'Modern Life'],
    coverImage: null,
  },
  {
    id: 'courage-is-calling',
    title: 'Courage is Calling',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 9,
    review: 'The first book in the Stoic Virtues trilogy, following the theme of courage as the foundation of moral strength and decisive living. Blending classical philosophy with modern examples, Holiday defines courage not simply as bold heroism but as a quiet, necessary trait of character—choosing what is right despite fear, uncertainty, or public pressure. Through vivid historical stories ranging from Greek philosophers and wartime leaders to activists like Florence Nightingale and modern whistleblowers, he shows how every era demands courage from ordinary people willing to act while others hesitate. Holiday argues that fear is universal but manageable through awareness and discipline. Courage isn\'t the absence of fear but moving forward despite it. Each short meditation-style chapter distills a timeless idea into a call to action.',
    tags: ['Stoicism', 'Philosophy', 'Courage'],
    coverImage: null,
  },
  {
    id: 'dose-effect',
    title: 'The DOSE Effect',
    author: 'TJ Power',
    yearRead: 2025,
    rating: 10,
    review: 'A neuroscience-based guide to improving mental health and performance by deliberately managing the four key brain chemicals that shape your daily experience: Dopamine, Oxytocin, Serotonin, and Endorphins—together forming the acronym DOSE. Power argues that modern life throws these chemicals out of balance, leading to low motivation, anxiety, mood swings, and burnout. Instead of relying on medication or willpower alone, he offers a framework for "resetting" your brain chemistry with simple, repeatable habits built into everyday life. Each section focuses on one chemical: Dopamine from effortful, meaningful activities; Oxytocin through genuine human connection; Serotonin linked to mood and energy, supported by gut health and time in nature; and Endorphins activated through movement, laughter, and physical challenge.',
    tags: ['Neuroscience', 'Well-being', 'Psychology'],
    coverImage: null,
  },
  {
    id: 'discipline-is-destiny',
    title: 'Discipline Is Destiny',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 9,
    review: 'The second book in the Stoic Virtues series, focusing on self-discipline as the hinge on which character, performance, and long-term success all turn. Holiday frames discipline not as harsh self-denial but as the art of governing yourself—your body, mind, emotions, and ambitions—so you can actually live according to your values instead of impulses. He organizes the book into three main domains: control of the body (health, energy, habits), control of the temperament (ego, emotions, reactions), and control of the soul (principles, purpose, integrity). Across short, punchy chapters, he uses stories from athletes, artists, generals, founders, and ancient philosophers to show how quiet, consistent discipline creates the conditions for freedom, excellence, and peace of mind.',
    tags: ['Stoicism', 'Philosophy', 'Self-Discipline'],
    coverImage: null,
  },
  {
    id: 'hooked',
    title: 'Hooked',
    author: 'Nir Eyal',
    yearRead: 2025,
    rating: 8,
    review: 'Explores the psychology behind why certain technologies and products become so addictive. Eyal introduces the Hook Model, a four-step framework that explains how companies design experiences that keep users coming back. The steps are: Trigger, Action, Variable Reward, and Investment. A trigger sparks an action, which then leads to a variable reward that creates anticipation and dopamine-driven motivation. Finally, the user makes an investment—time, reputation, data, or effort—that increases the likelihood of repeating the behavior. Eyal blends behavioral psychology, neuroscience, and business strategy to show how small decisions in product design exploit our natural desire for connection, validation, and novelty. While being "hooked" isn\'t always negative, he also raises ethical questions, urging creators to design responsibly.',
    tags: ['Product Design', 'Psychology', 'Business'],
    coverImage: null,
  },
  {
    id: 'slow-productivity',
    title: 'Slow Productivity',
    author: 'Cal Newport',
    yearRead: 2025,
    rating: 8,
    review: 'Argues that modern "hustle culture" has created pseudo-productivity: constant emails, Slack messages, and busyness that look like work but crowd out meaningful output. Newport proposes an alternative philosophy built on three principles: do fewer things, work at a natural pace, and obsess over quality. Doing fewer things means aggressively limiting active projects and obligations so you can give deep attention to what truly matters. Working at a natural pace means accepting that high-quality knowledge work happens in waves and seasons, not endless sprints, and building in periods of lower intensity. Obsessing over quality means trading short-term volume and visibility for long-term craftsmanship, using standout results as leverage for more autonomy and better work conditions over time.',
    tags: ['Productivity', 'Work Culture', 'Deep Work'],
    coverImage: null,
  },
  {
    id: 'digital-minimalism',
    title: 'Digital Minimalism',
    author: 'Cal Newport',
    yearRead: 2025,
    rating: 9,
    review: 'Lays out a philosophy for using technology intentionally instead of letting it fragment your time, attention, and sense of self. Newport defines digital minimalism as focusing your online time on a small number of carefully chosen, optimized activities that strongly support your values—and then happily missing out on everything else. He grounds this in three principles: clutter is costly (every extra app or feed taxes your attention), optimization is important (deciding how you use a tool is as important as whether you use it), and intentionality is satisfying (being deliberate about tech use feels better than being pulled around by algorithms). A core practice he recommends is a 30-day digital declutter: temporarily removing optional technologies, then slowly reintroducing only those that clearly serve your life, with strict rules around their use.',
    tags: ['Minimalism', 'Technology', 'Well-being'],
    coverImage: null,
  },
  {
    id: 'five-types-wealth',
    title: 'The 5 Types of Wealth',
    author: 'Sahil Bloom',
    yearRead: 2025,
    rating: 8,
    review: 'Challenges the idea that money is the only form of success and argues that a truly "rich" life is built across five dimensions: Time Wealth, Social Wealth, Mental Wealth, Physical Wealth, and Financial Wealth. Bloom draws on research and interviews to show how chasing financial gain alone often leads to regret, while deliberate investment in time freedom, relationships, mental clarity, health, and money together creates durable satisfaction. The book is structured as a practical blueprint with reflection questions, historical context, and "three pillars" for each wealth category, plus concrete tools like time audits, relationship mapping, purpose exercises, and basic financial independence strategies. Bloom emphasizes that these five types are interconnected: neglecting health for career, or relationships for money, eventually destabilizes the entire portfolio of your life.',
    tags: ['Personal Finance', 'Well-being', 'Life Philosophy'],
    coverImage: null,
  },
  {
    id: 'right-thing-right-now',
    title: 'Right Thing, Right Now',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 9,
    review: 'The third book in the Stoic Virtues series, centering on justice—doing what is fair, kind, and right—as the virtue that gives meaning to all the others. Holiday argues that courage, discipline, and wisdom become dangerous if they are not guided by a strong sense of justice. For the Stoics, justice is not abstract theory but a daily practice of considering how your actions affect other people and choosing the option that contributes to the common good, even when it is inconvenient, risky, or goes against the crowd. The book is built from short chapters and historical stories to show how real people translated principles into action under pressure. Holiday emphasizes that most of us already know what the "right thing" is in a given situation; the real challenge is doing it now instead of delaying, rationalizing, or waiting for someone else to step up.',
    tags: ['Stoicism', 'Philosophy', 'Decision Making'],
    coverImage: null,
  },
  {
    id: 'comfort-crisis',
    title: 'The Comfort Crisis',
    author: 'Michael Easter',
    yearRead: 2025,
    rating: 10,
    review: 'Argues that modern life—climate-controlled, overfed, constantly entertained—has made us physically weaker, mentally more fragile, and less fulfilled than humans who regularly faced challenge and uncertainty. Easter weaves research from evolutionary biology, psychology, and medicine with his own 33-day hunting expedition in the Alaskan backcountry to show how "comfort creep" has removed the natural stressors our bodies and minds evolved to handle, leaving us sedentary, anxious, and disconnected. The book offers a practical blueprint for reintroducing discomfort in everyday life: long walks carrying weight, intermittent hunger or fasting, turning down temperature comfort, unplugging from digital stimulation, spending extended time outdoors, and contemplating mortality. These forms of intentional hardship quiet mental clutter, improve health markers, sharpen focus, and expand what you believe you\'re capable of.',
    tags: ['Health', 'Psychology', 'Modern Life'],
    coverImage: null,
  },
  {
    id: 'million-dollar-weekend',
    title: 'Million Dollar Weekend',
    author: 'Noah Kagan',
    yearRead: 2025,
    rating: 9,
    review: 'A highly tactical guide to starting a real business fast by acting instead of over-planning. Kagan\'s core thesis is that most would-be entrepreneurs never start because of two main fears: the fear of starting and the fear of asking (for money, feedback, or help). To break through this, he lays out a weekend playbook: pick a simple idea that solves a real problem, talk directly to potential customers, and validate the idea by getting at least a few people to pay within 48 hours—before building anything significant. This "sell first, build later" approach flips the usual pattern of months spent on logos, websites, and planning without a single sale. The book mixes mindset and step-by-step execution, introducing challenges like the Coffee Challenge to train rejection resilience and build Creator\'s Courage.',
    tags: ['Entrepreneurship', 'Business', 'Startup'],
    coverImage: null,
  },
  {
    id: 'obstacle-is-way',
    title: 'The Obstacle Is the Way',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 9,
    review: 'A modern introduction to Stoicism built around a single idea from Marcus Aurelius: "The impediment to action advances action. What stands in the way becomes the way." Holiday argues that every difficulty contains within it a potential advantage, if you can change how you see it, how you act, and what you endure. The book is structured into three disciplines: Perception (seeing obstacles objectively and looking for opportunity within adversity), Action (taking persistent, creative, focused steps on what you can control), and Will (building inner resilience and using hardship to strengthen character). Through short, story-driven chapters, Holiday illustrates these principles with historical and contemporary examples who faced heavy setbacks and used them as fuel rather than excuses. It\'s a mindset manual: a reminder that obstacles are inevitable, but victimhood is optional.',
    tags: ['Stoicism', 'Philosophy', 'Resilience'],
    coverImage: null,
  },
  {
    id: 'scarcity-brain',
    title: 'Scarcity Brain',
    author: 'Michael Easter',
    yearRead: 2025,
    rating: 9,
    review: 'Explains why humans constantly feel like they don\'t have enough—of food, money, stuff, status, or stimulation—even though we live in an age of unprecedented abundance. Easter argues that our brains evolved in environments of real scarcity, where over-seeking was a survival advantage, but this "scarcity brain" now misfires in modern life, driving overeating, overconsumption, digital addiction, and endless comparison. At the core of the book is the scarcity loop: a behavioral pattern made of three parts—an opportunity to gain something of value, unpredictable rewards, and quick repeatability. Easter travels and interviews scientists, slot-machine designers, monks, technologists, and psychologists to show how modern systems are built to trigger our scarcity brain. He offers ways to step off this loop: spotting scarcity cues, practicing subtraction, and using gratitude and mindfulness to shift from "not enough" to "enough."',
    tags: ['Psychology', 'Neuroscience', 'Behavior'],
    coverImage: null,
  },
  {
    id: 'stillness-is-key',
    title: 'Stillness Is the Key',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 9,
    review: 'Argues that in a world of noise, speed, and constant demands, the decisive advantage is inner stillness—a calm, clear mind that can see reality accurately and act wisely. Holiday draws on Stoicism, Buddhism, Christianity, and other traditions to show that almost every wisdom school revered some form of stillness. He defines stillness not as inactivity, but as a state of clarity, presence, and emotional steadiness that allows you to think clearly, resist impulses, and stay centered even when life is chaotic. The book is structured around three domains—Mind, Spirit, and Body—which must work in harmony for true stillness. Through historical and modern examples, Holiday shows that stillness is a trainable skill and a prerequisite for good decisions, deep relationships, creativity, and lasting performance.',
    tags: ['Stoicism', 'Philosophy', 'Mindfulness'],
    coverImage: null,
  },
  {
    id: 'book-of-charlie',
    title: 'The Book of Charlie',
    author: 'David Von Drehle',
    yearRead: 2025,
    rating: 10,
    review: 'A biography-meets-life-manual built around the story of Charlie White, a Kansas City doctor who lived from 1905 to 2014. Von Drehle befriends Charlie as an elderly neighbor and, through years of conversations, reconstructs a life that spans horse-and-buggy days to smartphones. Rather than treating Charlie as a curiosity, the author uses his story to explore how one person can keep adapting, stay curious, and remain fundamentally optimistic through a century of rapid, often brutal change. The core lesson is Charlie\'s blend of Stoic acceptance and forward-leaning optimism. His simple guiding ideas—"do the right thing," "keep your daubers up," "let it go and hold on," and "nobody\'s going to do it for you; you\'ve got to do your own paddling"—become a philosophy for resilience: accept loss, act anyway, stay decent, and keep saying yes to life\'s opportunities.',
    tags: ['Biography', 'Life Lessons', 'Wisdom'],
    coverImage: null,
  },
  {
    id: 'so-good-cant-ignore',
    title: "So Good They Can't Ignore You",
    author: 'Cal Newport',
    yearRead: 2025,
    rating: 7,
    review: 'Attacks the popular advice to "follow your passion," arguing that it often leads to chronic dissatisfaction, risky career jumps, and unrealistic expectations. Studying scientists, entrepreneurs, craftspeople, and knowledge workers, Newport concludes that most people who end up loving their work did not start with a clear passion; instead, they developed enthusiasm over time as they became highly skilled and valuable. He proposes the career capital theory: the traits of great jobs—autonomy, creativity, impact, and a sense of mission—are rare and valuable, so to obtain them you must first build rare and valuable skills. This requires adopting a craftsman mindset ("What can I offer the world?") rather than a passion mindset ("What does the world offer me?") and engaging in years of deliberate practice that steadily increases your expertise.',
    tags: ['Career', 'Skills', 'Success'],
    coverImage: null,
  },
  {
    id: 'founder-force-multiplier',
    title: 'The Founder & The Force Multiplier',
    author: 'Adama Hergenrother',
    yearRead: 2025,
    rating: 8,
    review: 'A playbook for building a powerful, strategic partnership between a Founder (visionary leader) and a Force Multiplier (typically an Executive Assistant or Chief of Staff). The authors define a force multiplier as far more than an admin; it is a right-hand partner who amplifies the founder\'s impact by organizing the vision, aligning priorities, managing communication, and handling the "miscellaneous 80%" of work so the leader can focus on the highest-value activities. The book covers practical topics like clarifying roles and expectations, creating shared systems for decision-making and communication, building trust and radical transparency, and running effective meetings and cadences. The tone is candid and tactical, with checklists, examples, and stories of what worked and what failed in their own journey.',
    tags: ['Business', 'Leadership', 'Entrepreneurship'],
    coverImage: null,
  },
  {
    id: 'essentialism',
    title: 'Essentialism',
    author: 'Greg McKeown',
    yearRead: 2025,
    rating: 9,
    review: 'About doing fewer things, but doing them far better. McKeown argues that in a world of endless options, notifications, and demands, most people live as "Nonessentialists," saying yes to almost everything, spreading themselves thin, and confusing busyness with impact. An Essentialist, by contrast, believes that only a very small number of things are truly vital and that the rest is "noise." Their core question is not "How can I fit it all in?" but "What do I want to go big on?"—and they accept real trade-offs instead of pretending everything is equally important. McKeown structures the book around three disciplines: Explore, Eliminate, Execute. Throughout, he contrasts the mindset of the Nonessentialist ("I have to," "It\'s all important") with the Essentialist ("I choose to," "Only a few things matter"), inviting you to live more by design than by default.',
    tags: ['Productivity', 'Minimalism', 'Focus'],
    coverImage: null,
  },
  {
    id: 'twelve-week-year',
    title: 'The 12 Week Year',
    author: 'Brian Moran',
    yearRead: 2025,
    rating: 7,
    review: 'Argues that traditional annual goal setting breeds procrastination and complacency: people feel they have "plenty of time," so they delay focused action until it\'s too late. The authors propose shrinking your planning horizon to 12-week "years," each treated as a full execution cycle with its own clear goals, plan, and review. This condensed timeframe creates urgency and clarity: you set 1–3 specific, measurable goals for the next 12 weeks, identify a small set of keystone actions that drive those goals, and then build a weekly plan that translates them into concrete tasks on the calendar. The system rests on a few disciplines: crafting a compelling long-term vision, writing a focused 12-week plan, using process control to ensure consistent execution, and building accountability through scorecards and regular check-ins.',
    tags: ['Productivity', 'Goal Setting', 'Time Management'],
    coverImage: null,
  },
  {
    id: 'building-second-brain',
    title: 'Building a Second Brain',
    author: 'Thiago Forte',
    yearRead: 2025,
    rating: 7,
    review: 'Teaches a system for managing information so your mind can focus on thinking, not remembering. Forte argues that modern knowledge workers drown in notes, links, documents, and ideas, then forget 90% of them precisely when they\'re needed. Instead of relying on memory, he proposes building a "Second Brain"—a digital, trusted repository where you continuously store and refine useful information so it is easy to retrieve and use later. The method revolves around two main frameworks: P.A.R.A. for organizing (Projects, Areas, Resources, Archives) and C.O.D.E. for workflow (Capture, Organize, Distill, Express). Forte emphasizes that the point is not perfect tools but consistent habits: capturing small pieces of knowledge, revisiting and refining them in context of active projects, and letting your Second Brain quietly accumulate compound interest.',
    tags: ['Productivity', 'Knowledge Management', 'Organization'],
    coverImage: null,
  },
  {
    id: 'adhd-advantage',
    title: 'Unblocking the ADHD Advantage',
    author: 'Dr. Anders Hansen',
    yearRead: 2025,
    rating: 9,
    review: 'Reframes ADHD from a pure "disorder" into a trait with deep evolutionary roots and real modern strengths, while still being honest about its challenges. Hansen explains that traits like restlessness, novelty-seeking, impulsivity, and the ability to hyperfocus likely helped hunter-gatherers survive—driving exploration, risk-taking, and rapid reaction in dangerous or changing environments. In today\'s world of classrooms, cubicles, and constant digital distractions, those same traits can clash with rigid systems, leading to concentration problems; but in the right contexts they map onto creativity, entrepreneurial drive, resilience, and big-picture thinking. A major focus is practical, holistic strategies: understanding your own profile, shaping environments to reduce constant beeps and temptations, using structure and routines that work with ADHD rather than against it.',
    tags: ['ADHD', 'Neuroscience', 'Psychology'],
    coverImage: null,
  },
  {
    id: 'think-again',
    title: 'Think Again',
    author: 'Adam Grant',
    yearRead: 2025,
    rating: 8,
    review: 'Explores why the ability to rethink—to question your own opinions, update your beliefs, and change your mind—is becoming more important than being consistently right. Grant argues that many of us get stuck in three unhelpful modes: the preacher (defending our beliefs), the prosecutor (attacking others\' arguments), and the politician (seeking approval), instead of approaching life like a scientist who treats ideas as hypotheses to be tested. He shows how overconfidence, confirmation bias, and cognitive laziness keep us attached to outdated views. Grant then turns to how to build a habit of rethinking in everyday life: confident humility, seeking out disagreeable givers who challenge us with good intentions, and asking better questions in disagreements. The book encourages readers to regularly update their identities and see themselves as lifelong learners whose beliefs and skills can evolve.',
    tags: ['Psychology', 'Critical Thinking', 'Learning'],
    coverImage: null,
  },
  {
    id: 'becoming-bulletproof',
    title: 'Becoming Bulletproof',
    author: 'Evy Poumpouras',
    yearRead: 2025,
    rating: 8,
    review: 'Part memoir, part self-defense and psychology manual built from the author\'s career as a U.S. Secret Service agent protecting presidents and interrogating suspects. Poumpouras defines becoming "bulletproof" as developing mental toughness, emotional control, and strong situational awareness so you can stay calm under pressure, protect yourself and others, and handle conflict without freezing or overreacting. The book is organized around three broad shields: protection (personal security basics, scanning environments, trusting intuition), reading people (interpreting body language, micro-expressions, tone, and inconsistencies to detect deception), and influence (priming how others see you, holding firm boundaries, having hard conversations). Throughout, Poumpouras emphasizes that real courage is quiet and internal: you build it through small, repeated acts of facing discomfort, correcting weaknesses, and refusing to see yourself as a victim.',
    tags: ['Mental Toughness', 'Psychology', 'Security'],
    coverImage: null,
  },
  {
    id: 'psychology-of-money',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    yearRead: 2025,
    rating: 10,
    review: 'A collection of 19 short, story-driven chapters about how people behave with money, rather than how money works in theory. Housel\'s central claim is that financial success depends far more on behavior—patience, humility, self-control, and long-term thinking—than on IQ, math skills, or perfect models. Because everyone grows up with different experiences around wealth, risk, and markets, we each build a unique "money story," which explains why smart people often make bad financial decisions. Housel distinguishes between getting rich and staying rich: bold bets can build wealth, but staying wealthy requires frugality, diversification, and deep respect for luck and risk. He emphasizes the power of compounding and argues that avoiding catastrophic mistakes matters more than chasing maximum returns. Real wealth is what you don\'t see: savings, options, and the freedom to control your time.',
    tags: ['Personal Finance', 'Psychology', 'Investing'],
    coverImage: null,
  },
  {
    id: 'wisdom-takes-work',
    title: 'Wisdom Takes Work',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 9,
    review: 'The fourth and final book in the Stoic Virtues series, focusing on wisdom as the virtue that makes courage, discipline, and justice safe and effective. Holiday argues that wisdom is not a mystical gift but a skill: the ability to make sound judgments in complex, uncertain situations, built slowly through study, reflection, and lived experience. In an age that rewards hot takes, tribalism, and certainty, he makes the case that true wisdom requires doing the opposite: slowing down, questioning your own beliefs, seeking nuance, and staying open to changing your mind. Holiday structures the book as a journey that moves from cultivating the right mindset through education and contemplation, to resisting the temptations of ego, power, and intellectual arrogance, and finally to embodying wisdom as a daily way of life. He emphasizes practical disciplines: reading widely and critically, listening more than speaking, and embracing mental struggle instead of shortcuts.',
    tags: ['Stoicism', 'Philosophy', 'Wisdom'],
    coverImage: null,
  },
];

// Helper function to get books by rating (for filtering)
export const getBooksByRating = (minRating) => {
  return books.filter(book => book.rating >= minRating);
};

// Helper function to get top rated books
export const getTopRatedBooks = (limit = 5) => {
  return books
    .sort((a, b) => b.rating - a.rating)
    .slice(0, limit);
};

// Helper function to get books by tag
export const getBooksByTag = (tag) => {
  return books.filter(book => book.tags.includes(tag));
};
