// Book recommendations data with 10-point rating system

export const books = [
  {
    id: 'unfuck-your-brain',
    title: 'Unfuck Your Brain',
    author: 'Dr. Faith Harper',
    yearRead: 2025,
    rating: 8,
    order: 1,
    review: 'There is something about people just saying bad words and not trying to bullshit you with fancy words and technical jargon, just that makes this book worth reading; On the content side it really explains very well how trauma is not only death, an accident or a big event, I was very fortunate with the way I emigrated and yet, there is very subtle trauma that has developed in me because of that. In the hyperconnected world of anxiety, disconnection, and unhappiness, we should all know how to handle our trauma.',
    tags: ['Psychology', 'Mental Health', 'Self-Help'],
    coverImage: null,
  },
  {
    id: 'little-book-ikigai',
    title: 'Little Book of Ikigai',
    author: 'Ken Mogi',
    yearRead: 2025,
    rating: 9,
    order: 2,
    review: 'Read it now, keep it close, in a couple years read again and remember yourself to be in the present, to enjoy what you do for the sake of doing it, not for money, not for fame, but to master something you enjoy and to slow down from the hustle culture; the Japanese culture has a certain reputation for a reason, let\'s learn from it.',
    tags: ['Philosophy', 'Japanese Culture', 'Purpose'],
    coverImage: null,
  },
  {
    id: 'nagomi',
    title: 'Nagomi',
    author: 'Ken Mogi',
    yearRead: 2025,
    rating: 9,
    order: 3,
    review: 'This book basically tells you to let it be; life changes, new traditions are made, others are blended with new beliefs and the best thing we can do is accept it. Just like Ikigai, it is a great small book to have close by, and give it a read every now and then.',
    tags: ['Philosophy', 'Japanese Culture', 'Balance'],
    coverImage: null,
  },
  {
    id: 'tiny-habits',
    title: 'Tiny Habits',
    author: 'B.J. Fogg',
    yearRead: 2025,
    rating: 10,
    featured: true,
    order: 4,
    review: 'All you need to know of this book is that there is a Behavioral Lab in Stanford and many applications algorithms and designs are based on the research done there by B.J. Fogg; the more you read about habits, productivity, digital minimalism and such, the more you will encounter B.J. Fogg\'s behavioral model. This book maybe won\'t keep you extremely interested like a good movie, but it sure has some great insights to how our mind works and how to leverage that to your favor and for me, it triggered an avalanche of changes that stuck with me this year, better nutrition, physical and mental health and in general a better enjoyment of life.',
    tags: ['Productivity', 'Habits', 'Behavior Change'],
    coverImage: null,
  },
  {
    id: 'feel-good-productivity',
    title: 'Feel Good Productivity',
    author: 'Ali Abdaal',
    yearRead: 2025,
    rating: 6,
    order: 5,
    review: 'I read this book because I saw many videos in Ali\'s YouTube channel that truly stuck with me, I discovered one of my favorite books of this year on a 4-part series he did about The D.O.S.E. Effect, but I would not recommend his book as much as I would recommend his YouTube channel; he mentions a lot the idea of doing what you love and making your day to day fun which at least for me does not really have any true meaning or actionable insights.',
    tags: ['Productivity', 'Well-being', 'Self-Help'],
    coverImage: null,
  },
  {
    id: 'thinking-fast-slow',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    yearRead: 2025,
    rating: 8,
    order: 6,
    review: 'I won\'t lie; this book was somewhat boring; not because it is not good or well written, but I exclusively read for information and knowledge which means that many books I read are quite dense, and while I found many of the insights presented by this book fascinating it took me a long time to finish it. I still need to rate this book very high because it has a ton of good information, but I think most people will struggle to read through it.',
    tags: ['Psychology', 'Behavioral Economics', 'Decision Making'],
    coverImage: null,
  },
  {
    id: 'hacker-mindset',
    title: 'The Hacker Mindset',
    author: 'Garrett Gee',
    yearRead: 2025,
    rating: 4,
    order: 7,
    review: 'I think it is impossible to remember every detail and teaching of a book; I usually rate how much I liked a book by the facts I remember about it and the number of highlighted chapters in my index or facts throughout the read, while I remember liking the cover of this book, it seems to be the only thing I remember.',
    tags: ['Business', 'Entrepreneurship', 'Mindset'],
    coverImage: null,
  },
  {
    id: 'stolen-focus',
    title: 'Stolen Focus',
    author: 'Johann Hari',
    yearRead: 2025,
    rating: 10,
    featured: true,
    order: 8,
    review: 'While I was walking at an old library in Dallas, I found this book on a bookshelf and without knowing read the introduction and first chapter there totally submerged by Johann\'s story; disconnecting is very hard in the current hyperconnected world and this book was one of the first reminders of the year for me that I am in control of my attention as long as I set my environment for it. Definitely one of my favorite books of this year.',
    tags: ['Psychology', 'Attention', 'Modern Life'],
    coverImage: null,
  },
  {
    id: 'courage-is-calling',
    title: 'Courage is Calling',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    order: 9,
    review: 'This one is going to be a bit repetitive but basically every book from Ryan Holiday is a great bedside table book; you get to bed, read your main book and then read one or two of the short stories his books have, all lessons on life that have been around for centuries dating back to ancient Greek to world war II heroes. Rinse and repeat, his formula works for every single book, trust me, I have read them (almost) all this year.',
    tags: ['Stoicism', 'Philosophy', 'Courage'],
    coverImage: null,
  },
  {
    id: 'dose-effect',
    title: 'The DOSE Effect',
    author: 'TJ Power',
    yearRead: 2025,
    rating: 10,
    featured: true,
    order: 10,
    review: 'Today the internet offers so much information that we usually do not know where to start, what to pay attention to, and we overlook the most valuable information because it does not catch our eye as easily as dumb dances and shocking news. How our brain works is one of the most intricate mysteries of humankind, and this book gives you a very solid foundation on how to balance your main brain chemicals to feel happier, less stressed, more motivated and more connected to your environment. Productivity meets Digital Minimalism with some psychology and science involved.',
    tags: ['Neuroscience', 'Well-being', 'Psychology'],
    coverImage: null,
  },
  {
    id: 'discipline-is-destiny',
    title: 'Discipline Is Destiny',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    order: 11,
    review: 'This one is going to be a bit repetitive but basically every book from Ryan Holiday is a great bedside table book; you get to bed, read your main book and then read one or two of the short stories his books have, all lessons on life that have been around for centuries dating back to ancient Greek to world war II heroes. Rinse and repeat, his formula works for every single book, trust me, I have read them (almost) all this year.',
    tags: ['Stoicism', 'Philosophy', 'Self-Discipline'],
    coverImage: null,
  },
  {
    id: 'hooked',
    title: 'Hooked',
    author: 'Nir Eyal',
    yearRead: 2025,
    rating: 7,
    order: 12,
    review: 'If you want to create a new app or sell a new product by exploiting the way our brain gets hooked, this is a book for you. I was very curious on how apps and algorithms have evolved and how doom scrolling has become a thing, this book navigates through how many products use these tricks to grow and keep you coming back for more, good if you are a conspiracy theorist on how we are being puppeteered by a secret society.',
    tags: ['Product Design', 'Psychology', 'Business'],
    coverImage: null,
  },
  {
    id: 'slow-productivity',
    title: 'Slow Productivity',
    author: 'Cal Newport',
    yearRead: 2025,
    rating: 8,
    order: 13,
    review: 'Read it, just read it. It is short, easy to read, and exposes the reality most people live with burnout and stress due to believing that being productive means working 24/7.',
    tags: ['Productivity', 'Work Culture', 'Deep Work'],
    coverImage: null,
  },
  {
    id: 'digital-minimalism',
    title: 'Digital Minimalism',
    author: 'Cal Newport',
    yearRead: 2025,
    rating: 10,
    order: 14,
    review: 'The first thing I did after reading this book was turned off all notifications from my phone; I have read a lot about social media and dopamine, productivity, well-being and in today\'s world it all comes back to controlling our time in the digital world, use it as a tool, not a way of living.',
    tags: ['Minimalism', 'Technology', 'Well-being'],
    coverImage: null,
  },
  {
    id: 'five-types-wealth',
    title: 'The 5 Types of Wealth',
    author: 'Sahil Bloom',
    yearRead: 2025,
    rating: 9,
    order: 15,
    review: 'I have always had this idea in my head of the pillars of life and that each of us have different priorities for these pillars; some may consider their soul or religious pillar to be very important in their life but others might prefer to have a strong professional or work pillar, giving a lot of importance to their careers. To me, Sahil Bloom expresses this in his own way, reminding us that money is not everything if you do not have time or even time can be useless if you have poor physical and mental health. Overall is a good reminder that we are getting increasingly drawn to a Hustle first culture rather than enjoy living in a more balanced and healthy way.',
    tags: ['Personal Finance', 'Well-being', 'Life Philosophy'],
    coverImage: null,
  },
  {
    id: 'right-thing-right-now',
    title: 'Right Thing, Right Now',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    order: 16,
    review: 'This one is going to be a bit repetitive but basically every book from Ryan Holiday is a great bedside table book; you get to bed, read your main book and then read one or two of the short stories his books have, all lessons on life that have been around for centuries dating back to ancient Greek to world war II heroes. Rinse and repeat, his formula works for every single book, trust me, I have read them (almost) all this year.',
    tags: ['Stoicism', 'Philosophy', 'Decision Making'],
    coverImage: null,
  },
  {
    id: 'comfort-crisis',
    title: 'The Comfort Crisis',
    author: 'Michael Easter',
    yearRead: 2025,
    rating: 10,
    featured: true,
    order: 17,
    review: 'A friend mentioned to me that every commercial in the US sells you comfort and safety, it is all about being painless and easy and this is true for almost everything these days even at the gym when you are supposed to be training hard we do it in climate-controlled warehouses and specialized machines that target whatever muscle we want; The Comfort Crisis is an eye-opening experience on how this new super comfortable world we are living in is affecting us more than we think, and the reason why many of us are considered by older generations like the fragile generation, a generation who do not face challenges anymore in any way. A great reminder to push ourselves more every now and then, and that comfort is not everything.',
    tags: ['Health', 'Psychology', 'Modern Life'],
    coverImage: null,
  },
  {
    id: 'million-dollar-weekend',
    title: 'Million Dollar Weekend',
    author: 'Noah Kagan',
    yearRead: 2025,
    rating: 9,
    order: 18,
    review: 'A mentor and friend recommended this book to me when I was telling him about an App idea, I would be lying if I said that I applied everything in it and made a million dollars, but that is also because I still need to break a couple mental barriers to just fail, which is a big part of this book, learn to fail, start today, validate an idea and go fail over and over.\n\nA highly tactical guide to starting a real business fast by acting instead of over-planning. Kagan\'s core thesis is that most would-be entrepreneurs never start because of two main fears: the fear of starting and the fear of asking (for money, feedback, or help). To break through this, he lays out a weekend playbook: pick a simple idea that solves a real problem, talk directly to potential customers, and validate the idea by getting at least a few people to pay within 48 hours—before building anything significant. This "sell first, build later" approach flips the usual pattern of months spent on logos, websites, and planning without a single sale. The book mixes mindset and step-by-step execution, introducing challenges like the Coffee Challenge to train rejection resilience and build Creator\'s Courage.',
    tags: ['Entrepreneurship', 'Business', 'Startup'],
    coverImage: null,
  },
  {
    id: 'obstacle-is-way',
    title: 'The Obstacle Is the Way',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 9,
    order: 19,
    review: 'This one is going to be a bit repetitive but basically every book from Ryan Holiday is a great bedside table book; you get to bed, read your main book and then read one or two of the short stories his books have, all lessons on life that have been around for centuries dating back to ancient Greek to world war II heroes. Rinse and repeat, his formula works for every single book, trust me, I have read them (almost) all this year.',
    tags: ['Stoicism', 'Philosophy', 'Resilience'],
    coverImage: null,
  },
  {
    id: 'scarcity-brain',
    title: 'Scarcity Brain',
    author: 'Michael Easter',
    yearRead: 2025,
    rating: 9,
    order: 20,
    review: 'Another great book on how our brain works, why we crave more and how the world around us exploits that daily.',
    tags: ['Psychology', 'Neuroscience', 'Behavior'],
    coverImage: null,
  },
  {
    id: 'stillness-is-key',
    title: 'Stillness Is the Key',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    order: 21,
    review: 'This one is going to be a bit repetitive but basically every book from Ryan Holiday is a great bedside table book; you get to bed, read your main book and then read one or two of the short stories his books have, all lessons on life that have been around for centuries dating back to ancient Greek to world war II heroes. Rinse and repeat, his formula works for every single book, trust me, I have read them (almost) all this year.',
    tags: ['Stoicism', 'Philosophy', 'Mindfulness'],
    coverImage: null,
  },
  {
    id: 'book-of-charlie',
    title: 'The Book of Charlie',
    author: 'David Von Drehle',
    yearRead: 2025,
    rating: 10,
    featured: true,
    order: 22,
    review: 'The best book I have read this year, I wish I had known Charlie.\n\nA biography-meets-life-manual built around the story of Charlie White, a Kansas City doctor who lived from 1905 to 2014. Von Drehle befriends Charlie as an elderly neighbor and, through years of conversations, reconstructs a life that spans horse-and-buggy days to smartphones. Rather than treating Charlie as a curiosity, the author uses his story to explore how one person can keep adapting, stay curious, and remain fundamentally optimistic through a century of rapid, often brutal change. The core lesson is Charlie\'s blend of Stoic acceptance and forward-leaning optimism. His simple guiding ideas—"do the right thing," "keep your daubers up," "let it go and hold on," and "nobody\'s going to do it for you; you\'ve got to do your own paddling"—become a philosophy for resilience: accept loss, act anyway, stay decent, and keep saying yes to life\'s opportunities.',
    tags: ['Biography', 'Life Lessons', 'Wisdom'],
    coverImage: null,
  },
  {
    id: 'so-good-cant-ignore',
    title: "So Good They Can't Ignore You",
    author: 'Cal Newport',
    yearRead: 2025,
    rating: 9,
    order: 23,
    review: 'Have you ever played a videogame or started a new hobby where you were not that good at it? Many of us then will say we do not like that activity but then we keep trying and learning, therefore getting better at it, now all of a sudden we like that game or hobby. I think this book is a bit of that, not everything is about passion, it is also about hundreds of hours of getting better at something to build passion.\n\nAttacks the popular advice to "follow your passion," arguing that it often leads to chronic dissatisfaction, risky career jumps, and unrealistic expectations. Studying scientists, entrepreneurs, craftspeople, and knowledge workers, Newport concludes that most people who end up loving their work did not start with a clear passion; instead, they developed enthusiasm over time as they became highly skilled and valuable. He proposes the career capital theory: the traits of great jobs—autonomy, creativity, impact, and a sense of mission—are rare and valuable, so to obtain them you must first build rare and valuable skills. This requires adopting a craftsman mindset ("What can I offer the world?") rather than a passion mindset ("What does the world offer me?") and engaging in years of deliberate practice that steadily increases your expertise.',
    tags: ['Career', 'Skills', 'Success'],
    coverImage: null,
  },
  {
    id: 'founder-force-multiplier',
    title: 'The Founder & The Force Multiplier',
    author: 'Adama Hergenrother',
    yearRead: 2025,
    rating: 8,
    order: 24,
    review: 'This one is quite unique because it was recommended to me as I started a job as the Executive Assistant of the CEO of a Startup in Austin, so it might not be of interest for everyone; with that out of the way if you are in a position where you support a leadership role or, if you are in a leadership role I think this book has many good examples and insights on running a business and making sure that the people around you are always helping you and your business grow.',
    tags: ['Business', 'Leadership', 'Entrepreneurship'],
    coverImage: null,
  },
  {
    id: 'essentialism',
    title: 'Essentialism',
    author: 'Greg McKeown',
    yearRead: 2025,
    rating: 9,
    order: 25,
    review: 'When we have so many things to do, we believe we must do them all. It is through the scarcity of certain things that we find value and this book does a good job reminding us to do less, enjoy more; want less and appreciate more.\n\nAbout doing fewer things, but doing them far better. McKeown argues that in a world of endless options, notifications, and demands, most people live as "Nonessentialists," saying yes to almost everything, spreading themselves thin, and confusing busyness with impact. An Essentialist, by contrast, believes that only a very small number of things are truly vital and that the rest is "noise." Their core question is not "How can I fit it all in?" but "What do I want to go big on?"—and they accept real trade-offs instead of pretending everything is equally important. McKeown structures the book around three disciplines: Explore, Eliminate, Execute. Throughout, he contrasts the mindset of the Nonessentialist ("I have to," "It\'s all important") with the Essentialist ("I choose to," "Only a few things matter"), inviting you to live more by design than by default.',
    tags: ['Productivity', 'Minimalism', 'Focus'],
    coverImage: null,
  },
  {
    id: 'twelve-week-year',
    title: 'The 12 Week Year',
    author: 'Brian Moran',
    yearRead: 2025,
    rating: 7,
    order: 26,
    review: 'I think the idea of the book is good, but I would rather have just watched Ali Abdaal\'s video of it.\n\nArgues that traditional annual goal setting breeds procrastination and complacency: people feel they have "plenty of time," so they delay focused action until it\'s too late. The authors propose shrinking your planning horizon to 12-week "years," each treated as a full execution cycle with its own clear goals, plan, and review. This condensed timeframe creates urgency and clarity: you set 1–3 specific, measurable goals for the next 12 weeks, identify a small set of keystone actions that drive those goals, and then build a weekly plan that translates them into concrete tasks on the calendar. The system rests on a few disciplines: crafting a compelling long-term vision, writing a focused 12-week plan, using process control to ensure consistent execution, and building accountability through scorecards and regular check-ins.',
    tags: ['Productivity', 'Goal Setting', 'Time Management'],
    coverImage: null,
  },
  {
    id: 'building-second-brain',
    title: 'Building a Second Brain',
    author: 'Thiago Forte',
    yearRead: 2025,
    rating: 7,
    order: 27,
    review: 'I got bored halfway through, but the fundamental teachings of the book are still good, it reminds us of the amount of information that we are exposed to today and that most of us have not adapted our systems to properly store, access and digest that information when needed.',
    tags: ['Productivity', 'Knowledge Management', 'Organization'],
    coverImage: null,
  },
  {
    id: 'adhd-advantage',
    title: 'Unblocking the ADHD Advantage',
    author: 'Dr. Anders Hansen',
    yearRead: 2025,
    rating: 9,
    order: 28,
    review: 'I was diagnosed with ADHD here in the US and decided not to just stay with that, did not take Adderall or even keep going to therapy, instead I started learning a lot about ADHD and this book was beyond amazing.',
    tags: ['ADHD', 'Neuroscience', 'Psychology'],
    coverImage: null,
  },
  {
    id: 'think-again',
    title: 'Think Again',
    author: 'Adam Grant',
    yearRead: 2025,
    rating: 8,
    order: 29,
    review: 'There is nothing more important in this life than knowing that we are wrong, read this, Think Again about what you know and how you approach being mistaken.\n\nExplores why the ability to rethink—to question your own opinions, update your beliefs, and change your mind—is becoming more important than being consistently right. Grant argues that many of us get stuck in three unhelpful modes: the preacher (defending our beliefs), the prosecutor (attacking others\' arguments), and the politician (seeking approval), instead of approaching life like a scientist who treats ideas as hypotheses to be tested. He shows how overconfidence, confirmation bias, and cognitive laziness keep us attached to outdated views. Grant then turns to how to build a habit of rethinking in everyday life: confident humility, seeking out disagreeable givers who challenge us with good intentions, and asking better questions in disagreements. The book encourages readers to regularly update their identities and see themselves as lifelong learners whose beliefs and skills can evolve.',
    tags: ['Psychology', 'Critical Thinking', 'Learning'],
    coverImage: null,
  },
  {
    id: 'psychology-of-money',
    title: 'The Psychology of Money',
    author: 'Morgan Housel',
    yearRead: 2025,
    rating: 10,
    featured: true,
    order: 30,
    review: 'No one teaches us about money, and this book is a great place to start understanding our own relationship and habits with it.',
    tags: ['Personal Finance', 'Psychology', 'Investing'],
    coverImage: null,
  },
  {
    id: 'wisdom-takes-work',
    title: 'Wisdom Takes Work',
    author: 'Ryan Holiday',
    yearRead: 2025,
    rating: 8,
    order: 31,
    review: 'This one is going to be a bit repetitive but basically every book from Ryan Holiday is a great bedside table book; you get to bed, read your main book and then read one or two of the short stories his books have, all lessons on life that have been around for centuries dating back to ancient Greek to world war II heroes. Rinse and repeat, his formula works for every single book, trust me, I have read them (almost) all this year.',
    tags: ['Stoicism', 'Philosophy', 'Wisdom'],
    coverImage: null,
  },
  {
    id: 'becoming-bulletproof',
    title: 'Becoming Bulletproof',
    author: 'Evy Poumpouras',
    yearRead: 2025,
    rating: 8,
    order: 32,
    review: 'The memoir part of this book is very interesting, just consider that Evy was in the World Trade Center during 9/11 and you will be interested in her stories right away; and the more "practical-guide" part of this book has many insights that probably most people don\'t even think about. It might get boring for some, but it is a very interesting book.',
    tags: ['Memoir', 'Psychology', 'Leadership'],
    coverImage: null,
  },
  // --- 2026 ---
  {
    id: 'die-with-zero',
    title: 'Die With Zero',
    author: 'Bill Perkins',
    yearRead: 2026,
    rating: 8,
    order: 1,
    review: 'In a world where everything pushes us to buy more, Die with Zero is a needed slap in the face. It reminds us that money is just a tool, not a scoreboard, and that experiences, memories, and people matter more than anything we could accumulate. This book is a quiet rebellion against consumerism and an invitation to give our money a real purpose while we can still enjoy it.',
    tags: ['Personal Finance', 'Life Philosophy', 'Minimalism'],
    coverImage: null,
  },
  {
    id: 'when-breath-becomes-air',
    title: 'When Breath Becomes Air',
    author: 'Paul Kalanithi',
    yearRead: 2026,
    rating: 10,
    featured: true,
    order: 2,
    review: 'When Breath Becomes Air is a Pulitzer finalist for a reason. I loved how Paul moves between medicine, literature, and his own story, showing both the technical side of neurosurgery and the very human, fragile reality behind every patient. Reading his reflections as he faces terminal cancer forces you into a conversation with death you cannot escape.',
    tags: ['Memoir', 'Medicine', 'Philosophy'],
    coverImage: null,
  },
  {
    id: 'bird-by-bird',
    title: 'Bird by Bird',
    author: 'Anne Lamott',
    yearRead: 2026,
    rating: 7,
    order: 3,
    review: 'A book for writers, but I still found a lot of life in its pages beyond the act of writing itself. Even if you never plan to publish anything, many of her lessons apply to how you approach any long, uncertain project in life: you move forward "bird by bird," one small step at a time. As someone who enjoys writing, this book felt like having an older, slightly chaotic friend telling me to keep going and not take myself too seriously.',
    tags: ['Writing', 'Creativity', 'Self-Help'],
    coverImage: null,
  },
  {
    id: 'ride-of-a-lifetime',
    title: 'The Ride of a Lifetime',
    author: 'Robert Iger',
    yearRead: 2026,
    rating: 9,
    order: 4,
    review: 'We should all read more stories of other people\'s success—not for the highlight reel, but for the mindset behind it. What I appreciated most about his stories was his humility; even as the CEO of Disney, he constantly returns to being human first and a businessman second. The way he shares his decisions, doubts, and lessons makes you feel like you\'re inside the mind of someone running one of the world\'s most influential companies. A book to always prepare ourselves for the future by learning from someone who has already walked a very demanding path.',
    tags: ['Leadership', 'Business', 'Memoir'],
    coverImage: null,
  },
  {
    id: 'outliers',
    title: 'Outliers',
    author: 'Malcolm Gladwell',
    yearRead: 2026,
    rating: 7,
    order: 5,
    review: 'It was a very interesting book to understand how success is not only about talent, but also about opportunity and environment.',
    tags: ['Psychology', 'Success', 'Sociology'],
    coverImage: null,
  },
  {
    id: 'mans-search-for-meaning',
    title: "Man's Search for Meaning",
    author: 'Viktor Frankl',
    yearRead: 2026,
    rating: 9,
    order: 6,
    review: 'The stories of a concentration camp survivor and his search for meaning in life. A very interesting book to understand the power of the mind and how we can find meaning in even the darkest of times. Unfortunately a situation that is still happening today in many parts of the world.',
    tags: ['Philosophy', 'Psychology', 'Memoir'],
    coverImage: null,
  },
  {
    id: 'slight-edge',
    title: 'The Slight Edge',
    author: 'Jeff Olson',
    yearRead: 2026,
    rating: 7,
    order: 7,
    review: 'The power of habits is a topic that has been covered a lot in the last few years, this book is very good but there are others on the topic that are better.',
    tags: ['Productivity', 'Habits', 'Self-Help'],
    coverImage: null,
  },
  {
    id: 'tribe',
    title: 'Tribe',
    author: 'Sebastian Junger',
    yearRead: 2026,
    rating: 8,
    order: 8,
    review: 'We as humans are social creatures and this book is a great reminder of the power of community and how we can benefit from it. We are forgetting to be closer to each other and to the community around us.',
    tags: ['Psychology', 'Sociology', 'Community'],
    coverImage: null,
  },
  {
    id: 'fierce-conversations',
    title: 'Fierce Conversations',
    author: 'Susan Scott',
    yearRead: 2026,
    rating: 8,
    order: 9,
    review: 'We should all learn how to communicate better, be brave, be honest and authentic in our conversations.',
    tags: ['Communication', 'Leadership', 'Business'],
    coverImage: null,
  },
  {
    id: 'art-of-spending-money',
    title: 'The Art of Spending Money',
    author: 'Morgan Housel',
    yearRead: 2026,
    rating: 9,
    order: 10,
    review: 'This book is a great reminder that money is not everything and it is not the only way to measure success. Time, love and health can and will make you way happier than money will.',
    tags: ['Personal Finance', 'Psychology', 'Money'],
    coverImage: null,
  },
];

// Helper function to get books by rating (for filtering)
export const getBooksByRating = (minRating) => {
  return books.filter(book => book.rating >= minRating);
};

// Helper function to get top rated books
export const getTopRatedBooks = (limit = 5) => {
  return books
    .sort((a, b) => b.rating - a.rating)
    .slice(0, limit);
};

// Helper function to get books by tag
export const getBooksByTag = (tag) => {
  return books.filter(book => book.tags.includes(tag));
};
